initial commit
RndIG/car-service pull request #1
Opened 2024-11-14 04:45 UTC by RndIG

2024-11-14 08:24 UTC, Alexmansar requested changes
@RndIG Hi)) In general good job) few commets)

2024-11-14 08:24 UTC, Alexmansar commented on src/main/java/com/carservice/entities/Employee.java
> +public class Employee {
why we need it? I mean empty class

2024-11-14 08:24 UTC, Alexmansar commented on src/main/java/com/carservice/workshop/Workshop.java
> +
remove this lines please

2024-11-16 22:18 UTC, RndIG commented on src/main/java/com/carservice/entities/Employee.java
> +public class Employee {
Placeholder for Employee entity, for usage as assigned employee later

2024-11-16 22:38 UTC, merged

2024-11-17 08:08 UTC, Alexmansar commented on src/main/java/com/carservice/entities/Employee.java
> +public class Employee {
Ok) in general, please don't add code that isn't needed yet)